### ISSUE TITLE
docker-compose with prometheus & grafana

### ISSUE THREAD

**Issue by MattKetmo** [kilnfi/cosmos-validator-watcher#64]
Create a docker-compose to quickly set up prometheus demo with a default grafana dashboard

**Comment by hexmark21** [comment]
Hey @MattKetmo, 

I created a [cosmos-watcher-stack](https://github.com/21state/cosmos-watcher-stack/) to simplify the deployment and management of watcher instances using docker compose, along with default grafana dashboard.

Let me know what you think and if we can include a reference to it in the main repository :)
Thank you.

**Comment by MattKetmo** [comment]
Hey @hexmark21 thanks very much for this contribution 👍

Sure, I can add a section in the README to mention your repo. I'll do next week.
Or we can copy the resources directly in this repo ? As you prefer.

**Comment by hexmark21** [comment]
Thanks @MattKetmo, I appreciate it. 

I think it would be better to link to my repo, as it keeps things more maintainable and allows me to update the resources independently.
